### ISSUE TITLE
Another 500 internal error on 220.video-processing benchmark. Please assist

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#116]
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST -data '{"bucket": {
        "input": "220.video-processing-0-input-d510f263-fb8e-49",
        "output": "220.video-processing-0-output-82a4c8c3-3ddf-43"
      },
      "object": {
        "duration": 1,
        "key": "city.mp4",
        "op": "watermark"
      }
}' --header 'Content-Type: application/json'

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>JSONDecodeError(&#039;Expecting value: line 1 column 1 (char 0)&#039;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 172, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1129, in json
    return json_loads(b)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 98, in &lt;lambda&gt;
    json_loads = lambda s: json_lds(touni(s))
  File &quot;/usr/local/lib/python3.7/json/__init__.py&quot;, line 348, in loads
    return _default_decoder.decode(s)
  File &quot;/usr/local/lib/python3.7/json/decoder.py&quot;, line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File &quot;/usr/local/lib/python3.7/json/decoder.py&quot;, line 355, in raw_decode
    raise JSONDecodeError(&quot;Expecting value&quot;, s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
        </body>
    </html>
curl: (3) nested brace in URL position 12:
{"bucket": {
        "input": "220.video-processing-0-input-d510f263-fb8e-49",
        "output": "220.video-processing-0-output-82a4c8c3-3ddf-43"
      },
      "object": {
        "duration": 1,
        "key": "city.mp4",
        "op": "watermark"
      }
}
           ^
(python-venv) jchigu@SEBS:~$

**Comment by mcopik** [comment]
The exception was caused by invoking function with empty input. Looking at your command, it seems that it is incorrect - you passed `-data` instead of `--data`. I guess that cURL ignored the incorrect option, leading to invoking the function with no input.

In the future, input sanitization (#118) and the `perf-cost` experiment for local benchmarks will help (#119) since users will not have to write invocations manually. Unfortunately, the local environment was developed originally as a test ground and thus it does not have full capabilities needed.

In the meantime, I recommend to write a simple script that will start function containers, invoke them as needed for your experiments, and then close containers. You can either use the sample inputs provided in the output JSON (all modern programming languages have capabilities for loading and parsing a JSON file), or if you use Python, you can import the `input.py` file directly from the benchmark directory and call the input generation function. Both options will help you since you will make invocations automatic and faster to conduct in series, and will help you to avoid incorrect invocations and errors caused by copy-pasting commands :-)
